.zha_device_info.update:
  description: "Update ZHA device info."
  fields: {}

.zha_device_info.export:
  description: "Export ZHA device info to JSON."
  fields:
    path:
      description: "The path to save the exported JSON file."
      example: "/config/zha_devices.json"
