update:
  name: Update
  description: "Update ZHA device info."
  fields: {}

export:
  name: Export
  description: "Export ZHA device info to JSON."
  fields:
    path:
      name: Path
      description: "The path to save the exported JSON file."
      example: "/config/zha_devices.json"

